### PR TITLE
feat: use resolve to allow node_modules resolution

### PR DESCRIPTION
**Pull request by mrsvt**

### CODE REVIEW

**Comment by pveyes** [comment]
What's difference between this and `require.resolve` ?

**Comment by mrsvt** [comment]
`require.resolve` requires at least Node v8.9.0 to include custom paths resolution, while [resolve](https://github.com/browserify/resolve) support most node versions as shown in the [test results](https://travis-ci.org/browserify/resolve/builds/482605271?utm_source=github_status&utm_medium=notification). Also, if we want to use `require.resolve`, we need to upgrade Jest to at least [v23.4.0](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2340). We can add fallback to `path.resolve` on `require.resolve` error, but I think it's better to go with `resolve`.

**Comment by mrsvt** [comment]
I just notice that `raw.macro` is tested against Node 6 which also means supporting it.

https://github.com/pveyes/raw.macro/blob/master/.travis.yml#L8

**Comment by pveyes** [comment]
@sayuti-daniel we can drop support for node < 8.9 similar to webpack 4 upgrade. I'd prefer to use native fn. Feel free to modify travis.yml & update deps

**Review by pveyes — APPROVED** [review]
Nice thanks

**Pull request merged**
